spring:
  datasource:
    url: jdbc:h2:mem:autheniq
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  h2:
    console.enabled: true
server:
  port: 8080
